name: Daily_Stock_Monitor

on:
  schedule:
    - cron: '*/30 1-6 * * 1-5'
  workflow_dispatch:

# --- 加入這段程式碼 ---
permissions:
  contents: write
# --------------------

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 檢出儲存庫代碼
        uses: actions/checkout@v3
        
      # ... 中間維持您原本的設定 ...

      - name: 提交並推送到儲存庫
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git commit -m "Update stock data [skip ci]" || exit 0
          git push
